### ISSUE TITLE
and what the hell are both of them

### ISSUE THREAD

**Issue by nanderer** [nucleus-ffm/ultraswitch#1]
Ich hab deine readme gelsesen, ich hab versucht dein quellcode zu lesen, ich spreche kein python, ich weiß jetzt das es irgendwas mit audio zu tun hat da dort worte wie musik und podcast zu finden sind, was ich aber immer noch nicht weiß ist was ist reaper (außer das englische wort für Schniter) was ist ultraschall (außer schall der auf höheren frequenzen ist als das menschen ihn hören können), ich kann mir aber ziemlich sicher sein das beides hiermit nicht gemeint ist. Wäre cool die readme noch um ein zwei Sätze zu erweitern um den zweck dieser software für jederman (oder jede frau/jede person/ erverybody) in kontext zu setzen...

thx

**Comment by nucleus-ffm** [comment]
Danke für den Hinweis. Ich habe die Readme etwas ergänzt. Jetzt sollte es klarer sein, für was dieser Prototyp gedacht ist.

**Comment by nanderer** [comment]
Danke, vielleicht noch "DAW" um "(Digital Audio Workstation)" ergänzen ;)
